Declare dependencies

diff --git a/gh-lint-workflow b/gh-lint-workflow
--- a/gh-lint-workflow
+++ b/gh-lint-workflow
@@ -12,6 +12,15 @@ case "$1" in
   ;;
 esac
 
+if ! type -p node >/dev/null; then
+  echo "node not found: this tool requires a Node.js runtime" >&2
+  exit 1
+fi
+if ! type -p jq >/dev/null; then
+  echo "jq not found" >&2
+  exit 1
+fi
+
 make_input() {
   local input_fmt='{
     command: "parse-workflow",
